# Generated by Django 3.2.2 on 2021-05-10 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=100)),
                ('dev_id', models.IntegerField(max_length=3)),
                ('dev_type', models.CharField(max_length=100)),
                ('dev_ip', models.CharField(max_length=16)),
                ('dev_mac', models.CharField(max_length=18)),
                ('dev_info', models.CharField(max_length=100)),
                ('dev_tx_traffic', models.IntegerField(max_length=10)),
                ('dev_rx_traffic', models.IntegerField(max_length=10)),
                ('dev_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dev_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
