# Generated by Django 3.2.2 on 2021-06-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dev_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='dev_rx_traffic',
        ),
        migrations.RemoveField(
            model_name='device',
            name='dev_tx_traffic',
        ),
    ]
