# Generated by Django 3.2.2 on 2021-06-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0002_auto_20210613_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dev_status',
            field=models.CharField(default='Alive', max_length=5),
        ),
    ]
