# Generated by Django 3.2.2 on 2021-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0003_device_dev_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dev_rx_traffic',
            field=models.IntegerField(default='456787', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='dev_tx_traffic',
            field=models.IntegerField(default='987642', max_length=100),
        ),
    ]
