# Generated by Django 3.2.5 on 2021-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0004_auto_20210613_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dev_status_changed',
            field=models.IntegerField(default='0', max_length=1),
        ),
    ]
