# Generated by Django 3.2.5 on 2021-07-12 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0006_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
