# Generated by Django 3.2.5 on 2021-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0007_alert_alert_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_name',
            new_name='alert_dev',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_time',
            field=models.CharField(max_length=100),
        ),
    ]
