# Generated by Django 3.2.5 on 2021-07-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0008_auto_20210712_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dev_status',
            field=models.CharField(default='Alive', max_length=20),
        ),
    ]
