# Generated by Django 3.2.5 on 2021-07-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0010_auto_20210712_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_last_updated',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_rx_traffic',
            field=models.IntegerField(default='10000', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_tx_traffic',
            field=models.IntegerField(default='10000', max_length=100),
        ),
    ]
