# Generated by Django 3.2.5 on 2021-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0011_auto_20210713_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dev_rx_traffic',
            field=models.IntegerField(default='387654', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_tx_traffic',
            field=models.IntegerField(default='456987', max_length=100),
        ),
    ]
